name: Rebuild Pull Requests

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: write

jobs:
  rebuild-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rebuild Pull Requests
        uses: rhosys/github-action-rebuild-pull-requests@v1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}